version: "3"
services:
  rabbitmq:
    hostname: "rabbitmq"
    image: "rabbitmq:management-alpine"
    ports:
      - "15672:15672"
      - "5672:5672"

  elasticsearch:
    hostname: "elasticsearch"
    image: "elasticsearch:7.10.1"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    depends_on:
      - rabbitmq